### ISSUE TITLE
For Model API output, List, Map, Set should be JSON-ified properly

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#122]
When calling methods via the Model API, only integers, strings and booleans are returned using the proper JSON datatypes, all other data is converted to strings.  Container datatypes should be handled the following way:
- ABS list into JSON list
- ABS set into JSON list
- ABS map into JSON map

**Comment by afifun** [comment]
Hello Rudi,

I'm Afifun, master student of computer science at Faculty of Computer Science Universitas Indonesia [http://www.cs.ui.ac.id/].  Interest with this issue, because it’s related with my research proposal topic that I propose to build microservices framework by using ABS [I called ABS Microservices Framework*]. The framework will probably like Spring Boot [http://projects.spring.io/spring-boot/], Play Framework [https://www.playframework.com/] or Dropwizard [http://www.dropwizard.io/1.0.0/docs/].  The final result of my research is produce microservices framework that support Software Product Line Engineering [SPLE].

More about microservices [http://martinfowler.com/articles/microservices.html]
Most of microservices framework using JSON format for server’s data response  to client and I will do same in ABS Microservices Framework.

For this feature (JSON datatypes in ABS) , how far is already implemented in ABS?

*This research is part of research of Reliable Software Engineering Laboratory, Faculty of Computer Science Universitas Indonesia [http://rse.cs.ui.ac.id/?open=prices/index]

Sorry for my english before and freely ask if any question :)

**Comment by rudi** [comment]
Hi, there is no native JSON support planned in the language ABS.  This bug entry only relates to the (not yet documented) http api offered by the erlang simulator backend, specifically to how to encode responses to queries about object state and responses for external method calls.
Best of luck with your research!

**Comment by afifun** [comment]
Okey, Thank you for the information :)
