### ISSUE TITLE
Compiler crash when anonymous function accesses field

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#176]
The following code leads to a compiler crash:

```
module Test;
class Test() {
    Map<String,Int> components_map = map[];
    Unit init() {
        List<Int> test = map((String i) => lookupUnsafe(components_map,i))(
            list["aaa"]);
        }
}
```

**Comment by rudi** [comment]
reported by @jacopoMauro

**Comment by BjoernPetersen** [comment]
This is at least partially caused by FieldUse.getFreeVars() returning an empty set. Shouldn't it return `Collections.singleton(getName())` like it does for VarUse?

If so, IntelliJ tells me that only the Java backend uses the method, so someone who is familiar with it should probably give their OK for that change.

**Comment by rudi** [comment]
Since the Java backend is semi-broken already (one of those weekends I'll get to it!), I'm ok with the proposed change.
