### ISSUE TITLE
Methods without explicit `return` statement do not properly return `Unit`

### ISSUE THREAD

**Issue by larstvei** [abstools/abstools#251]
When running the following model with the erlang simulator:

```java
module FutureReadTest;

interface I { Unit m(); }

class C implements I { Unit m() { skip; } }

{
    I o = new C();
    Fut<Unit> f = o!m();
    Unit u = f.get;
    println(toString(u));
}
```

it prints `skip`.

Generally, it seems like the last expression of the method is what ends up being returned by a method of type `Unit`.

I think this is a bug, as the same program, but with the following main-block:

```java
{
    I o = new C();
    Fut<Unit> f = o!m();
    Unit u = f.get;
    Unit w = Unit;
    println(toString(u == w));
}
```

prints `False`.

**Comment by rudi** [comment]
Cute.  Seems nobody ever looked at the return value of these implicit return statements.  It's broken in the Maude backend, as well.  I'll probably just throw a `return Unit;` into the AST in case there's no return statement; all analysis tools that break because of this change were broken before as well :)

Fix incoming when I'm back in the office.
